// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.UUIDGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("uuids")]
        public Guid[] Uuids { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("version")]
        public long Version { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("variant")]
        public string Variant { get; set; }
    }
}
